name: mobile_app_for_country_info_with_theme_customization
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    -  .env
    -  assets/images/

  fonts:
    - family: Axiforma
      fonts:
        # - asset: assets/fonts/Kastelov - Axiforma Bold Italic.otf
        # - asset: assets/fonts/Kastelov - Axiforma Black.otf
        # - asset: assets/fonts/Kastelov - Axiforma Black Italic.otf
        # - asset: assets/fonts/Kastelov - Axiforma Bold.otf
        # - asset: assets/fonts/Kastelov - Axiforma Book.otf
        # - asset: assets/fonts/Kastelov - Axiforma Thin.otf
        - asset: assets/fonts/Kastelov - Axiforma Regular.otf
        # - asset: assets/fonts/Kastelov - Axiforma Medium.otf
    
